In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
c=np.arange(1,10,0.8) # range of values in array( 1 to 10 , 0.8 is step)
d = np.linspace(1,5,6) #set of values by Interval(divides 1 to 5 in 6 equal parts) 
print(c)
print(d)

[1.  1.8 2.6 3.4 4.2 5.  5.8 6.6 7.4 8.2 9.  9.8]
[1.  1.8 2.6 3.4 4.2 5. ]


In [140]:
print(a.ndim) # dimension off array
print(a.itemsize) #Byte size of each element
print(a.dtype)
print(a.size*a.itemsize) # memory Occupied
print(a.size) # number of elements in an array
print(b.shape) #shape of array(rows and columns)
print(a.mean())

1
4
int32
40
10
(2, 5)
5.5


In [33]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b = b.reshape(5,2)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [41]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b[0,2]) # slicing a row from certain row and column
print(b[0:,2]) # slicing element from all rows and a ceratin column

3
[3 8]


In [49]:
e=np.array([7,9,9,2,16,11,96])
print(e.min(),e.max(),e.sum())

2 96 150


In [55]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b.sum(axis=0)) # column wise addtion 1+6 , 2+7 ...
print(b.sum(axis=1)) # row wise addition 1+2+3+4+5=15 and 6+7+8+9+10=40
print(np.sqrt(a))
print(np.std(a)) # standard deviation
print(np.exp(a)) # exponential of aaray
print(np.log(a))
print(np.log10(a))
print(np.log2(a))

[ 7  9 11 13 15]
[15 40]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
2.8722813232690143
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809]


In [65]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
c= np.array([(11,12,13,14,15),(16,17,18,19,20)])
print(np.vstack((b,c))) #vertical merging of arrays
print(np.hstack((b,c))) #horizontal merging of arrays
print(b.ravel()) # coverting multi-dimensional to single dimensional

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
threeDArray = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [69]:
print(threeDArray[0][0][2])

3


In [73]:
print(threeDArray[0,0,2])

3


In [75]:
print(threeDArray.itemsize)

4


In [77]:
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [79]:
for i in threeDArray.flatten(): #all values get printed in single dimension
    print(i)

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6


In [85]:
print(threeDArray.flatten())
print(threeDArray.ravel())
print(threeDArray)

[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


## filling arrays with specific values

In [92]:
#zeros
z=np.zeros((5,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [98]:
#ones
o=np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [100]:
o = o.astype(int) # converting to integer values as default value is float
print(o)

[1 1 1 1 1]


In [104]:
ranges = np.arange(5.8,9.8,0.5)
print(ranges)

[5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [112]:
#linspace
linspace = np.linspace(3,6,10)
print(linspace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [108]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(matrix+2)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [114]:
pylist = [[1,2,3,4,5],[6,7,8,9,10]]
print(pylist*2) #doubles the list (copying of list)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [116]:
print(matrix.T) #coverts rows to column and columns to row

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [118]:
print(matrix[1,])

[ 6  7  8  9 10]


In [122]:
print('1-dimension')
full = np.full(10,5) # no.of elements and value
print(full)
print()
print('2-dimension')
full = np.full((2,2),5) # no.of elements and value
print(full)
print()
print('3-dimension')
full = np.full((2,5,4),5) # no.of elements and value
print(full)

1-dimension
[5 5 5 5 5 5 5 5 5 5]

2-dimension
[[5 5]
 [5 5]]

3-dimension
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [126]:
print([[1,2,3],[4,5]]+[[6,7,8],[9,10]]) # addition of two list

[[1, 2, 3], [4, 5], [6, 7, 8], [9, 10]]


In [138]:
matrix1=np.array([[1,2,3],[4,5,6],[13,14,15]])
matrix2=np.array([[4,5,6],[10,11,12],[16,17,18]])
print(matrix1 + matrix2)

# for multiplication shape of both arrays should be same
print(np.matmul(matrix1,matrix2))

[[ 5  7  9]
 [14 16 18]
 [29 31 33]]
[[ 72  78  84]
 [162 177 192]
 [432 474 516]]


In [150]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b.min())
print(b.max())
print(b.sum())
print(b.prod())
print(b.mean())
print(b.std())
print(round(b.var(),2))

1
16
136
2004189184
8.5
4.6097722286464435
21.25


In [152]:
print(b.min(axis=1))  # Minimum value in each row
print(b.max(axis=1))  # Maximum value in each row
print(b.sum(axis=1))  # Sum of elements in each row
print(b.prod(axis=1)) # Product of elements in each row
print(b.mean(axis=1)) # Mean of elements in each row
print(b.std(axis=1))  # Standard deviation in each row
print(np.round(b.var(axis=1), 2))  # Variance in each row (rounded to 2 decimals)


[ 1  5  9 13]
[ 4  8 12 16]
[10 26 42 58]
[   24  1680 11880 43680]
[ 2.5  6.5 10.5 14.5]
[1.11803399 1.11803399 1.11803399 1.11803399]
[1.25 1.25 1.25 1.25]


In [154]:
x=np.array([0,1,2,3,4])
y=np.array([0,1,2,3,4])
z=np.array([0,1,2,3,4])

np.hstack([x,y,z])

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [156]:
np.vstack([x,y,z])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [158]:
np.append(x,(2,3))

array([0, 1, 2, 3, 4, 2, 3])

In [166]:
new_array=np.array([1,2,3])
x=np.append([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [168]:
new_array=np.array([1,2,3])
x=np.append([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=1)
print(x)

[[1 2 3 1 2 3]
 [4 5 6 1 2 3]]


In [170]:
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6],
       [1, 1],
       [2, 2],
       [3, 3]])

In [176]:
arr = np.arange(11)
print(arr>4)
arr[arr>4]

[False False False False False  True  True  True  True  True  True]


array([ 5,  6,  7,  8,  9, 10])

In [178]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [180]:
np.random.rand(5)

array([0.57175449, 0.30132906, 0.39427412, 0.90366665, 0.55222651])

In [182]:
np.random.randint(10,20,(5,5)) # start value, stop value, shape

array([[17, 14, 13, 10, 11],
       [11, 15, 18, 17, 10],
       [19, 14, 15, 11, 15],
       [19, 16, 14, 13, 14],
       [12, 19, 14, 15, 18]])

In [188]:
letters=list('aeiou')
np.random.choice(letters,5,replace=False) #due to replace=False repetation of values will not occur

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [190]:
np.random.choice(letters,15,p=[0.4,0.3,0.1,0.1,0.1]) # p is probability of occurence of that particular letter

array(['a', 'e', 'a', 'a', 'e', 'a', 'e', 'a', 'e', 'o', 'u', 'a', 'a',
       'u', 'e'], dtype='<U1')

In [192]:
array = np.random.randint(10,20,(5,5))
np.save('array_file',array) #extension:.npy

In [194]:
a = np.load('array_file.npy')
print(a)

[[10 18 19 15 16]
 [17 11 16 17 12]
 [15 13 10 14 10]
 [12 18 18 12 15]
 [16 17 11 18 14]]
